services:
  app_vendas:
    build: backendvendas
    mem_limit: 512m
    ports:
      - "9494:9494"
    environment:
      PATHMATCHL: ant-path-matcher
      DB_URL: jdbc:mysql://wdpvendas:3306/loja_db?useTimezone=true&serverTimezone=America/Sao_Paulo
      DB_USER_NAME: root
      DB_PASSWORD: 102XfKCWeJ6fRBz6VFd5wZKZGlVEHdc1mGz0HwlHER8v5FC7e47m2muI0uN58oBF

      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: gregorio.des22@gmail.com
      SMTP_PASSWORD: fnxq fvlg ggtm mpzg
      SMTP_AUTH: true
      SMTP_ENABLE: true
      JWT_SECRET: my-secret-key

    restart: always
    depends_on:
      wdpvendas:
        condition: service_healthy

  wdpvendas:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 102XfKCWeJ6fRBz6VFd5wZKZGlVEHdc1mGz0HwlHER8v5FC7e47m2muI0uN58oBF
      MYSQL_PASSWORD: 102XfKCWeJ6fRBz6VFd5wZKZGlVEHdc1mGz0HwlHER8v5FC7e47m2muI0uN58oBF
      MYSQL_DATABASE: loja_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9090:80"
    environment:
      PMA_HOST: wdpvendas
      MYSQL_ROOT_PASSWORD: 102XfKCWeJ6fRBz6VFd5wZKZGlVEHdc1mGz0HwlHER8v5FC7e47m2muI0uN58oBF
    restart: always
    depends_on:
      wdpvendas:
        condition: service_healthy

